mode: simulation
board:
  squares: 8
  surface_z: 0.0
  square_size_mm: 45.0
arms:
  white:
    enabled: true
    color: white
    connection: usb
    serial_port: COM5
    origin_x: 120.0
    origin_y: -120.0
    rotation_deg: 0.0
    spacing: 45.0
    travel_z: 100.0
    grip_z: 24.19
    capture_x: 363.4176330566406
    capture_y: -120.75556945800781
    capture_z: -15.345335960388184
    velocity: 60
    acceleration: 60
    effector: suction
    limits:
      max_reach_mm: 380.0
      min_reach_mm: 100.0
      z_min_mm: -70.0
      z_max_mm: 160.0
    corners:
      A1:
        x: 203.53
        y: 81.0
        z: 24.0
      H8:
        x: 368.04
        y: -92.0
        z: 24.0
      H1:
        x: 198.86
        y: -89.33
        z: 21.67
      A8:
        x: 377.37
        y: 71.33
        z: 24.0
    square_overrides:
      A1:
        x: 203.53
        y: 81.0
        z: 20.0
      C1:
        x: 202.53
        y: 30.0
        z: 24.0
      E1:
        x: 200.53
        y: -15.0
        z: 23.0
      G1:
        x: 199.53
        y: -65.0
        z: 22.0
      B2:
        x: 229.53
        y: 58.0
        z: 23.0
      D2:
        x: 229.53
        y: 8.0
        z: 24.0
      F2:
        x: 224.53
        y: -42.0
        z: 23.0
      H2:
        x: 227.53
        y: -92.0
        z: 24.0
      A3:
        x: 255.53
        y: 82.0
        z: 24.0
      C3:
        x: 255.53
        y: 32.0
        z: 24.0
      E3:
        x: 255.53
        y: -18.0
        z: 24.0
      G3:
        x: 253.53
        y: -69.0
        z: 24.0
      B4:
        x: 282.53
        y: 54.0
        z: 24.0
      D4:
        x: 282.53
        y: 8.0
        z: 24.0
      F4:
        x: 282.53
        y: -42.0
        z: 24.0
      H4:
        x: 282.53
        y: -92.0
        z: 24.0
      A5:
        x: 308.53
        y: 80.0
        z: 29.0
      C5:
        x: 308.53
        y: 30.0
        z: 25.0
      E5:
        x: 308.53
        y: -20.0
        z: 25.0
      G5:
        x: 308.53
        y: -70.0
        z: 25.0
      B6:
        x: 334.53
        y: 56.0
        z: 25.0
      D6:
        x: 334.53
        y: 6.0
        z: 25.0
      F6:
        x: 334.53
        y: -44.0
        z: 25.0
      H6:
        x: 333.04
        y: -92.0
        z: 24.0
      H8:
        x: 368.04
        y: -92.0
        z: 24.0
      G7:
        x: 361.04
        y: -72.0
        z: 24.0
      E7:
        x: 358.04
        y: -22.0
        z: 24.0
      F8:
        x: 373.04
        y: -47.0
        z: 24.0
      D8:
        x: 379.04
        y: 3.0
        z: 24.0
      C7:
        x: 359.04
        y: 28.0
        z: 24.0
      B8:
        x: 376.04
        y: 48.0
        z: 24.0
      A7:
        x: 361.04
        y: 78.0
        z: 24.0
  black:
    enabled: true
    color: black
    connection: usb
    serial_port: COM4
    origin_x: 120.0
    origin_y: 120.0
    rotation_deg: 0.0
    spacing: 45.0
    travel_z: 100.0
    grip_z: 8.0
    capture_x: 349.8218078613281
    capture_y: -70.27952575683594
    capture_z: -18.888151168823242
    velocity: 60
    acceleration: 60
    effector: suction
    limits:
      max_reach_mm: 380.0
      min_reach_mm: 100.0
      z_min_mm: -70.0
      z_max_mm: 160.0
    corners:
      A1:
        x: 254.06324768066406
        y: -45.59947967529297
        z: -23.968368530273438
      H1:
        x: 254.06329345703125
        y: 129.40054321289062
        z: -23.96837043762207
      H8:
        x: 349.8218688964844
        y: 104.72049713134766
        z: -20.888229370117188
      A8:
        x: 349.8218078613281
        y: -70.27952575683594
        z: -18.888151168823242
vision:
  enabled: true
  camera_index: 1
  width: 640
  height: 480
  occupancy_threshold: 0.18
  method: template
engine:
  backend: auto
  stockfish_path: null
  think_time: 1.0
  minimax_depth: 3
  players:
    white: ai
    black: ai
match:
  max_moves: 0
  move_delay: 0.0
  verify_with_vision: true
